research_task:
  description: >
    Conduct a thorough research on weather in {city} for {date}
    Focus on:
    1. The most likely weather in {city} for {date}
    2. The weather report for {city} for {date}
    3. The weather history for {city} for {date}
    4. The weather forecast for {city} for {date}
    5. The weather trends for {city} for {date}
    6. The weather patterns for {city} for {date}
    7. The weather predictions for {city} for {date}
    8. The weather warnings for {city} for {date}
    9. The weather advisories for {city} for {date}
    10. The weather history for {city} for {date}
    11. The weather forecast for {city} for {date}
    12. The weather trends for {city} for {date}
    Make sure to organize your findings in a structured format with clear sections.
  expected_output: >
    A comprehensive document with the most likely weather in {city} for {date} covering all the topics mentioned above. 
    Give a prediction for the weather for {date} in the city of {city} based on the weather report. 
  agent: researcher

analysis_task:
  description: >
    Analyze the weather report and create a detailed report based on the weather 
    report in a clear and concise manner predicting the weather for {date} in the city of {city} 
    based on the weather report.
    The report should be well-structured with an executive summary, main sections, and conclusion.
    Your report should:
    1. Begin with an executive summary
    2. Include all key information from the weather report
    3. Provide insightful analysis of trends and patterns
    4. Offer a market outlook for company, noting that this should not be used for trading decisions
    5. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on {city} for {date} that presents the weather report with added analysis and insights. 
    The report should be well-structured with an executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/report.md
